apiVersion: v1
kind: Service
metadata:
  name: python-app-service
  namespace: devops-cluster
spec:
  type: NodePort
  selector:
    app: python-app
    version: green
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 31000
